import { CGray } from '@/constants/Colors'
import { StyleSheet } from 'react-native'
export const styles = StyleSheet.create({
  mainView: {
    paddingTop: 40,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    height: '100%',
    gap: 12,
  },
  pokeball: {
    position: 'absolute',
    opacity: 0.1,
    height: 200,
    width: 200,
    right: 20,
    top: 20,
  },
  header: {
    paddingLeft: 20,
    paddingRight: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  left: {
    display: 'flex',
    flexDirection: 'row',
  },
  btnBack: { paddingRight: 8 },
  btnBackTitle: {
    fontSize: 26,
    color: 'white',
    fontWeight: 'bold',
  },
  name: {
    fontSize: 26,
    fontWeight: 'bold',
    color: 'white',
  },
  id: {
    alignItems: 'center',
    fontWeight: 'bold',
    textAlign: 'right',
    flex: 1,
    color: 'white',
  },
  headerImg: {
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    height: 135,
    position: 'relative',
  },
  imageBackground: {
    position: 'absolute',
    zIndex: 10,
    top: 10,
    height: 200,
    width: 200,
  },
  info: {
    zIndex: 1,
    margin: 4,
    paddingLeft: 6,
    paddingRight: 6,
    borderRadius: 8,
    backgroundColor: CGray.white,
    flex: 1,
  },
  scrollView: {
    paddingLeft: 23,
    paddingRight: 23,
  },
  types: {
    paddingTop: 50,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
  },
  titleAbout: {
    textAlign: 'center',
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 16,
    fontWeight: 'bold',
  },
  bodyStatus: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  bodyStatusItem: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
  },
  bodyStatusItemMid: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: CGray.light,
  },
  bodyStatusIcon: {
    height: 16,
    width: 16,
  },
  infoGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  infoGroupAbilities: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 4,
    paddingBottom: 4,
    flex: 1,
  },
  bodyStatusValue: {
    fontSize: 12,
    fontWeight: '400',
  },
  infoName: {
    fontSize: 11,
    fontWeight: '300',
  },
  summary: {
    marginTop: 16,
    paddingTop: 16,
  },
  baseStatus: {},
  titleStatus: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingTop: 8,
    paddingBottom: 8,
  },
  status: {
    display: 'flex',
    flexDirection: 'row',
  },
  statusName: {
    fontWeight: 'bold',
    width: 40,
    textAlign: 'right',
    marginRight: 8,
    paddingTop: 2,
    paddingBottom: 2,
  },
  statusPoint: {
    paddingLeft: 8,
  },
  statusBar: {
    position: 'relative',
    flex: 1,
    height: 4,
    borderRadius: 6,
  },
  statusbarPercent: {
    position: 'absolute',
    flex: 1,
    height: '100%',
    borderRadius: 6,
  },
})
